### ISSUE TITLE
Comparison to Tauon Music Box

### ISSUE THREAD

**Issue by jansol** [hinto-janai/festival#21]
[Tauon Music Box](https://tauonmusicbox.rocks/) is a rather popular cross-platform modern music player written in (mostly) Python and with just the right amount of eye candy. As such it would be a great candidate for comparison (if you intend to add more players to that at some point).

**Comment by hinto-janai** [comment]
The comparison only contains music players I've used personally. It might be ingenuine to compare against software that I haven't even used (and don't really know the features, behaviors, performance of).

**Comment by jansol** [comment]
Fair enough.

I did some quick measurements to get a rough idea to satisfy my curiosity (not fully comparable due to differences in setup):

Specs
CPU: AMD Ryzen 5950x (32 threads)
RAM: 4x32GB DDR4 3200 MHz
HDD: WD Red 3TB something (library is stored here)
NVMe: Samsung SSD 980 Pro
OS: NixOS unstable (Linux 6.3.9 2023-06-21)
Both disks are using btrfs.


Collection:
 - 13838 tracks
 - 1067 albums
 - around 95% FLAC, 5% MP3

Cold import: ~30s to "import", 15min to scan tags
Cached import: ~1s
No errors after one that was fixed last year. (FLAC in an ID3 container imported fine but did not get played correctly)
Launch to fully rendered UI: ~1.7s
CPU use (idle): 0.7% of 1 core every couple of seconds
CPU use (playback): 4% of 1 core

As for features:
- Version: 7.6.6
- OS: Windows, Linux (SDL2)
- Open Source: yes
- Playlists: yes
- Sorting: yes, effectively instant
- Global Search (all tags, shows list of matches): accurate, ~1s
- Quick Find (all tags, jumps to first match): accurate, instant
- ReplayGain: yes
- Gapless playback: yes
- Internet (radio) streams: yes

Downsides:
- UI occasionally gets in very confused states
- HiDPI is supported but at least on my setup it often gets the scale wrong until I whisk the window to the secondary monitor.
