### ISSUE TITLE
(Bug?) Can't maximize the window

### ISSUE THREAD

**Issue by hardBSDk** [hinto-janai/festival#25]
## OS & Version

Festival v1.0.0
shukusai v0.0.1
Linux x64
894a5f1b8dfa14b8b73157511c0d4baab6d06063

## Bug

The window don't respect my screen resolution, I can't maximize it to see all window contents.

## Steps

1 - Open the program.
2 - Try to maximize the window with the button or keyboard shortcuts.

## Screenshots

![Screenshot from 2023-06-29 16-50-30](https://github.com/hinto-janai/festival/assets/55782009/102a35d2-50d8-41b0-b7a1-5010ba49ee2c)

**Comment by hinto-janai** [comment]
Can you try [`v1.0.1`](https://github.com/hinto-janai/festival/releases)? There's new pixel sizing options, and the window itself has a smaller minimum resolution.

I wasn't able to reproduce the maximize issue with KDE + 1920x1080.

What is your screen resolution and do you have any OS-wide pixel scaling enabled?

**Comment by hardBSDk** [comment]
@hinto-janai My screen resolution is 1366x768 using the default UI scale of GNOME 44.

I tested the version 1.0.1 and my issue is fixed, thanks! I'm loving this player.
