### ISSUE TITLE
Resetting collection stuck at 2.5%, walking directories. 

### ISSUE THREAD

**Issue by dragonattheend** [hinto-janai/festival#42]
## OS & Version
MacOS Ventura 13.4.1

## Bug
Resetting collection stuck at 2.5%, walking directories. 

## Steps
I keep my music on Dropbox. 
Due to the size, I can't have it all downloaded at once. 
When I add the folder with music in settings and then try to scan it gets stuck.
This does not happen if I add a folder with downloaded music (subdirectory).
This does not happen on Linux (EndeavourOS), which scans everything very quickly.

**Comment by dragonattheend** [comment]
Ok, so after 3 hours it actually did scan the library, but by downloading at least 50gb...

**Comment by hinto-janai** [comment]
Festival is for local data, if you have a network mounted disk which I assume you have with Dropbox, it'll be slow, probably too slow to scan in a reasonable amount of time.
