### ISSUE TITLE
Audio sometimes cuts out on high CPU usage

### ISSUE THREAD

**Issue by hinto-janai** [hinto-janai/festival#50]
## OS & Version
Festival v1.1.0

## Bug
When running other CPU intensive tasks, Festival's audio sometimes briefly cuts out.

Maybe this is acceptable if the CPU really was at 100%, but it happens even when not fully utilized. 

## Steps
1. Play audio
2. Run other CPU intensive task
3. Experience audio cut out

## Fix
Increase in-memory audio buffer, decrease message leeway for `Audio`, make decode loop more efficient.

**Comment by jansol** [comment]
As an optional thing, the audio thread could potentially be made realtime if rtkit is available?
