### ISSUE TITLE
Songs order for double album

### ISSUE THREAD

**Issue by kerzac** [hinto-janai/festival#66]
## OS & Version
Festival v1.3.0
macOS arm64
Collection v3
Audio v0
Playlist v0
State v1
Settings v2

## Bug
For double albums, the songs order is mixed up between the two discs

## Screenshots
In my folder, the order is separate for each disc:
<img width="247" alt="Capture d’écran 2023-09-04 à 18 00 22" src="https://github.com/hinto-janai/festival/assets/115277048/66d36fbd-5ad0-4a0c-9eb7-cc652eb48c80">

In festivalGUI, order is mixed between discs:
<img width="1249" alt="Capture d’écran 2023-09-04 à 18 01 56" src="https://github.com/hinto-janai/festival/assets/115277048/9c412e9f-c10d-4ad1-8b78-25fb90f53d9b">

Thank you in advance

**Comment by hinto-janai** [comment]
The songs are missing the `disc` metadata tag, you can add it with a metadata editor like https://github.com/metabrainz/picard.

With `disc` metadata, it should look something like this:

<img src="https://github.com/hinto-janai/festival/assets/101352116/6eb7090c-d4df-43b3-be7c-aa37ed921b8d" width="20%"/>

**Comment by kerzac** [comment]
Thanks for your reply and your great job !
